### ISSUE TITLE
SRIOV with Bond + VLAN using vrouter fails RHOSP 13 deployment during NIC provisioning.

### ISSUE THREAD

**Issue by linusali** [Juniper/contrail-container-builder#18]
RHOSP 13 Deployment with Contrail + Bond + VLAN and SRIOV fails with the following error message during the NIC provisioning by `os-net-config` on the host.
```
[2019/06/06 03:16:57 AM] [INFO] running ifup on interface: vlan500
[2019/06/06 03:16:57 AM] [ERROR] Failure(s) occurred when applying configuration
[2019/06/06 03:16:57 AM] [ERROR] stdout: ERROR     : [/sbin/ifup] PHYSDEV should be set for device vlan500
, stderr:
Traceback (most recent call last):
  File "/bin/os-net-config", line 10, in <module>
    sys.exit(main())
  File "/usr/lib/python2.7/site-packages/os_net_config/cli.py", line 308, in main
    activate=not opts.no_activate)
  File "/usr/lib/python2.7/site-packages/os_net_config/impl_ifcfg.py", line 1518, in apply
    raise os_net_config.ConfigurationError(message)
os_net_config.ConfigurationError: Failure(s) occurred when applying configuration
```

I think the best solution to this is to add `PHYSDEV` to the list of lines not commented by `network-functions-vrouter` in the following line. Though I don't know if that will cause any regressions. 

https://github.com/Juniper/contrail-container-builder/blob/a7db052315efd345376bec6dc577139d78e1e58c/containers/vrouter/base/network-functions-vrouter#L262

Please note that if I use a bond or a physical interface directly with `vhost0` then there is no issue.

**Comment by alexey-mr** [comment]
hm.. In rhosp setup  ifcfg files should not be touched by containers because they are prepared by tripleo (os-net..). So, the this sed should not be called at all in rhosp.

**Comment by alexey-mr** [comment]
fix with PHYSDEV is commited to master.
